[2023-11-28T19:09:07.827-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tpm1_workflow.run_gold manual__2023-11-28T22:08:43.732849+00:00 [queued]>
[2023-11-28T19:09:07.836-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tpm1_workflow.run_gold manual__2023-11-28T22:08:43.732849+00:00 [queued]>
[2023-11-28T19:09:07.836-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-28T19:09:07.855-0300] {taskinstance.py:1382} INFO - Executing <Task(PapermillOperator): run_gold> on 2023-11-28 22:08:43.732849+00:00
[2023-11-28T19:09:07.863-0300] {standard_task_runner.py:57} INFO - Started process 146861 to run task
[2023-11-28T19:09:07.868-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'tpm1_workflow', 'run_gold', 'manual__2023-11-28T22:08:43.732849+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tpm1.py', '--cfg-path', '/tmp/tmp8dmmjt8o']
[2023-11-28T19:09:07.869-0300] {standard_task_runner.py:85} INFO - Job 13: Subtask run_gold
[2023-11-28T19:09:07.918-0300] {task_command.py:416} INFO - Running <TaskInstance: tpm1_workflow.run_gold manual__2023-11-28T22:08:43.732849+00:00 [running]> on host data-engineer
[2023-11-28T19:09:08.001-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tpm1_workflow' AIRFLOW_CTX_TASK_ID='run_gold' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T22:08:43.732849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-28T22:08:43.732849+00:00'
[2023-11-28T19:09:08.020-0300] {execute.py:84} INFO - Input Notebook:  /home/marcos/airflow/notebooks/gold.ipynb
[2023-11-28T19:09:08.021-0300] {execute.py:85} INFO - Output Notebook: /home/marcos/airflow/notebooks/gold_output.ipynb
[2023-11-28T19:09:10.409-0300] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2023-11-28T19:09:11.412-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/marcos/anaconda3/envs/XPe-IGTI/lib/python3.8/site-packages/airflow/providers/papermill/operators/papermill.py", line 93, in execute
    pm.execute_notebook(
  File "/home/marcos/anaconda3/envs/XPe-IGTI/lib/python3.8/site-packages/papermill/execute.py", line 134, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/marcos/anaconda3/envs/XPe-IGTI/lib/python3.8/site-packages/papermill/execute.py", line 241, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [1]":
[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyspark[39;00m[38;5;21;01m.[39;00m[38;5;21;01msql[39;00m [38;5;28;01mimport[39;00m SparkSession

[0;31mModuleNotFoundError[0m: No module named 'pyspark'

[2023-11-28T19:09:11.428-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tpm1_workflow, task_id=run_gold, execution_date=20231128T220843, start_date=20231128T220907, end_date=20231128T220911
[2023-11-28T19:09:11.445-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task run_gold (
---------------------------------------------------------------------------
Exception encountered at "In [1]":
[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyspark[39;00m[38;5;21;01m.[39;00m[38;5;21;01msql[39;00m [38;5;28;01mimport[39;00m SparkSession

[0;31mModuleNotFoundError[0m: No module named 'pyspark'
; 146861)
[2023-11-28T19:09:11.490-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-28T19:09:11.502-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
